---
title: "Internal IV"
author: "Wanran Zhao"
date: '2023-05-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(plm)
```

```{r}
df_bp <- read_csv("/Users/zwanran/Desktop/ECMA31320/ECMA31320-project/data/gvcobp_transformed.csv")
```

```{r}
library(reticulate) 
dynpd <- import("pydynpd.regression", convert = TRUE)
fd <- import("pandas", convert=TRUE)
result <- df_bp$abond('n L(1:2).n w k | gmm(n, 2:4) gmm(w, 1:3) iv(k)', df, c('id', 'year'))
```


1. set time variable in r

# PLM
```{r}
unstationary = ecgrowth + logpop_M + logpopdens + logoutreg
stationary = logmountain + ethnic_fractionalization + religion_fractionalization + language_fractionalization + leg_british + opec
```

```{r eval=FALSE, include=FALSE}
# model = onset2COWCS ~ lag(onset2COWCS, 1) + s1 + s2 + s6 + s10 + s19 + ecgrowth + logpop_M + logpopdens + logoutreg + democracy + logmountain + ethnic_fractionalization + religion_fractionalization + language_fractionalization + leg_british + opec  | lag(log(onset2COWCS), 2)
model = onset2COWCS ~ lag(onset2COWCS, 1) + s1 + s2 + s6 + s10 + s19  | lag(log(onset2COWCS), 2)
z1 <- pgmm(model, data = df_bp, effect = "twoways", model = "twosteps")
summary(z1, robust = FALSE)

model = onset2COWCS ~ lag(onset2COWCS, 1) + s1 + s2 + s6 + s10 + s19 + ecgrowth + logpop_M + logpopdens + logoutreg + democracy + logmountain + ethnic_fractionalization + religion_fractionalization + language_fractionalization + leg_british + opec  | lag(log(onset2COWCS), 2:10)
z2 <- pgmm(model, data = df_bp, effect = "twoways", model = "twosteps", time.dummies = TRUE)
summary(z2, robust = FALSE)
```

